### ISSUE TITLE
程序无法运行，依赖分析出现感叹号

### ISSUE THREAD

**Issue by jiasss** [shenjackyuanjie/zed-win-build#2]
通过依赖分析发现 comctl32.dll 无法加载
![image](https://github.com/user-attachments/assets/938733b2-e8bb-4497-a1f7-e87df177d4b1)

**Comment by jiasss** [comment]
系统也存在comctl32.dll

**Comment by shenjackyuanjie** [comment]
诶，等一下，win10是吧……
有zed.log吗？

**Comment by shenjackyuanjie** [comment]
没log 我先 close 了（
有 log 再开新的 issue
