### ISSUE TITLE
可以帮忙修改一个源文件并打包一个0.151.1 版本?

### ISSUE THREAD

**Issue by lq0910** [shenjackyuanjie/zed-win-build#5]
按下面帖子方法修改可以解决win版本语言服务扩展问题
https://github.com/zed-industries/zed/issues/15004

万分感谢！搞定可以发红包感谢

**Comment by shenjackyuanjie** [comment]
我看看哈……

**Comment by lq0910** [comment]
@shenjackyuanjie  非常感谢，我自己尝试构建，rest依赖真是太慢了，运行缓慢

**Comment by shenjackyuanjie** [comment]
额……
麻烦说人话

**Comment by lq0910** [comment]
@shenjackyuanjie  晕。。。我说错话了？ ？ 我说我自己尝试构建rest包下载好慢。。

**Comment by shenjackyuanjie** [comment]
你是想说rust编译慢，还是rest的包下载的慢……

**Comment by lq0910** [comment]
@shenjackyuanjie  下载包慢哦，，哈哈，不是说你编译慢

**Comment by shenjackyuanjie** [comment]
我看看哈，能麻烦指出具体是那些修改/问题需要解决呢？

**Comment by lq0910** [comment]
@shenjackyuanjie  谢谢哈，我后来自己修改编译解决了
