### ISSUE TITLE
隔壁 zed-nightly 好久没更新了，能不能也在 scoop 上发个版自动更新一下？

### ISSUE THREAD

**Issue by iscas-zac** [shenjackyuanjie/zed-win-build#7]
如题。

**Comment by shenjackyuanjie** [comment]
讲道理我还没用过scoop 🤦‍♂️

**Comment by iscas-zac** [comment]
看了下刚刚更新了（[仓库](https://github.com/deevus/zed-windows-builds/releases/tag/20241122)）。话说兄弟是怎么玩上的 zed，而且还是 win 端的？有什么心得吗？

**Comment by shenjackyuanjie** [comment]
![image](https://github.com/user-attachments/assets/cf4be2b1-744a-481f-96e3-cc96388e61cb)

确实是刚刚修好了

emmm，看到“rust written editor”就过来玩了，之前看过 lapce 了，那玩意完成度…… 真不咋的
反正就是看到了就试试，然后发现完成度还不错，就整了
